//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpanadaReviewCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public int idDrink { get; set; }
        public int idRestaurant { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string imageSrc { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
